# Generated by Django 4.1.2 on 2022-11-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dates',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='usertype',
            field=models.CharField(max_length=50),
        ),
    ]
