# Generated by Django 4.1.2 on 2022-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_task_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
