# Generated by Django 4.1.2 on 2022-11-10 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_task_date_posted_task_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 2, 19, 0, 503459, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 21, 19, 0, 503459, tzinfo=datetime.timezone.utc)),
        ),
    ]
