# Generated by Django 4.1.2 on 2022-11-10 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_task_deadline_alter_task_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 2, 25, 23, 229470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
